### PR TITLE
parentheses after catch

### PR DESCRIPTION
**Pull request by lrobledo**
missing (ex) after catch clause causing errors

### CODE REVIEW

**Comment by lrobledo** [comment]
@P0lip Can you take a look at this?

**Comment by P0lip** [comment]
Hey!
My apologies for dropping a ball.
Is there any reason we need parentheses?
The syntax currently used is valid ([optional catch binding](https://2ality.com/2017/08/optional-catch-binding.html)).
Are you experiencing syntax errors? If so, what's your environment?

**Comment by lrobledo** [comment]
No worries! Thanks.

I don't have any errors when I run locally, but then when the code is run via Bitbucket pipelines it causes an error. I haven't run it recently so I don't have the error right now but I can get it and provide more details if that would be helpful.

It also looks like most of the other instances where `catch` is used it's followed by `(ex)` so this is the only line causing that error for me.

**Comment by fluffy-dutchman** [comment]
I am also seeing an issue with this same area when running in a Bamboo pipeline. Locally it works fine when running a spectral lint commend, unfortunately on the build agent it doesn’t work. The script I’m running it from is a simple Powershell script with: ‘spectral lint FILENAME -r RULESET’ and it tells me there is an error with the catch in a nimma file. Don’t have it directly in front of me. But I’ve been fighting with the issue all day.

**Comment by P0lip** [comment]
@lrobledo, @tnederveld Could you tell me which Node.js version are you using?

**Comment by fluffy-dutchman** [comment]
Just ran the pipeline and it reports back the node version is v8.11.3. Checked local and it’s running 10.16.3. I’ll look into when we can update the build agents, but might not be a quick thing

**Comment by fluffy-dutchman** [comment]
Was able to select a build agent that had a v10.23.0 version of NodeJS and it got passed the nimma file error. Granted, now I’m getting a ‘ts-node/register’ couldn’t be found, but sprectal did start the lint.

**Comment by lrobledo** [comment]
My build agent is using v8.11.3. 

I just installed that locally and it does look like that's the reason for the error. I'll see if I'm able to update the version...

Is there a reason we can't add the `(ex)` after the catch clause?

**Comment by lrobledo** [comment]
I looks like anything above v10.0.0 avoids the error

**Comment by P0lip** [comment]
> Is there a reason we can't add the (ex) after the catch clause?

We totally can, but what I'm trying to say is that your version of Node is not supported anyway.
I cannot guarantee you won't face any other errors using Spectral, as we don't support v8 anymore.
In fact, the minimum required version Spectral supports is Node 10.18, as can be seen in https://github.com/stoplightio/spectral/blob/develop/package.json#L33.

v8 is EOL. v10 enters EOL in April 2021, and the next version of Spectral will drop support for it.
https://nodejs.org/en/about/releases/

That said, I'd suggest you hop on v12 or, ideally, v14 if possible.
v14 is the latest LTS version. Spectral is going to support that particular version for roughly 2 years, thus you won't need to make any further changes in future, when a new Spectral version is released.

**Comment by P0lip** [comment]
Each Spectral release comes with binaries. Perhaps that's something you might be interested in?
https://github.com/stoplightio/spectral/releases/tag/v5.8.0
We also offer a simple script that automates the whole process https://github.com/stoplightio/spectral/blob/develop/scripts/install.sh -> `curl -L https://raw.githack.com/stoplightio/spectral/master/scripts/install.sh | sh`

**Comment by lrobledo** [comment]
Thanks! I didn't realize how old a version I was using. Should have caught that. I was able to update it without issues so now it's working for me. Thanks for those resources! I appreciate you taking the time to respond! I'll close out this issue.

**Pull request closed without merging**
